spring.application.name=ai-Screening
server.port=${AI_SCREENING_SERVER_PORT:8082}
spring.config.import=optional:classpath:env.properties

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${AI_SCREENING_KAFKA_GROUP_ID}

# Confluent Security
spring.kafka.properties.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_API_KEY}' password='${KAFKA_API_SECRET}';

#Consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.hireflow.ai_Screening.event.ApplicationSubmittedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.hireflow.ai_Screening.event

spring.kafka.producer.properties.spring.json.add.type.headers=false

hireflow.kafka.topics.application-submitted=${APPLICATION_SUBMITTED_TOPIC}
hireflow.kafka.topics.resume-analysis-completed=${RESUME_ANALYSIS_COMPLETED_TOPIC}
hireflow.kafka.topics.project-consistency-completed=${PROJECT_CONSISTENCY_COMPLETED_TOPIC}
hireflow.kafka.topics.inconsistency-review-completed=${INCONSISTENCY_REVIEW_COMPLETED_TOPIC}
hireflow.kafka.topics.screening-completed=${SCREENING_COMPLETED_TOPIC}
